# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw_settings_dialog.ui'
#
# Created: Wed Aug  5 09:24:10 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_hwSettingsDialog(object):
    def setupUi(self, hwSettingsDialog):
        hwSettingsDialog.setObjectName(_fromUtf8("hwSettingsDialog"))
        hwSettingsDialog.resize(610, 299)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(hwSettingsDialog.sizePolicy().hasHeightForWidth())
        hwSettingsDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(hwSettingsDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(hwSettingsDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabRecording = QtGui.QWidget()
        self.tabRecording.setObjectName(_fromUtf8("tabRecording"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabRecording)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblRecordingSettings = QtGui.QLabel(self.tabRecording)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblRecordingSettings.setFont(font)
        self.lblRecordingSettings.setObjectName(_fromUtf8("lblRecordingSettings"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblRecordingSettings)
        self.lblRecMic1 = QtGui.QLabel(self.tabRecording)
        self.lblRecMic1.setObjectName(_fromUtf8("lblRecMic1"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblRecMic1)
        self.cbRecMic1 = QtGui.QComboBox(self.tabRecording)
        self.cbRecMic1.setObjectName(_fromUtf8("cbRecMic1"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbRecMic1)
        self.lblRecMic2 = QtGui.QLabel(self.tabRecording)
        self.lblRecMic2.setEnabled(True)
        self.lblRecMic2.setObjectName(_fromUtf8("lblRecMic2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblRecMic2)
        self.cbRecMic2 = QtGui.QComboBox(self.tabRecording)
        self.cbRecMic2.setEnabled(True)
        self.cbRecMic2.setObjectName(_fromUtf8("cbRecMic2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbRecMic2)
        self.lblRecSamplFreq = QtGui.QLabel(self.tabRecording)
        self.lblRecSamplFreq.setEnabled(False)
        self.lblRecSamplFreq.setObjectName(_fromUtf8("lblRecSamplFreq"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblRecSamplFreq)
        self.cbRecSampFreq = QtGui.QComboBox(self.tabRecording)
        self.cbRecSampFreq.setEnabled(False)
        self.cbRecSampFreq.setObjectName(_fromUtf8("cbRecSampFreq"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbRecSampFreq)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tabRecording, _fromUtf8(""))
        self.tabRecording1 = QtGui.QWidget()
        self.tabRecording1.setObjectName(_fromUtf8("tabRecording1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabRecording1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tubeSettingsLayout = QtGui.QFormLayout()
        self.tubeSettingsLayout.setObjectName(_fromUtf8("tubeSettingsLayout"))
        self.lblTubeForm = QtGui.QLabel(self.tabRecording1)
        self.lblTubeForm.setObjectName(_fromUtf8("lblTubeForm"))
        self.tubeSettingsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblTubeForm)
        self.cbTubeForm = QtGui.QComboBox(self.tabRecording1)
        self.cbTubeForm.setObjectName(_fromUtf8("cbTubeForm"))
        self.cbTubeForm.addItem(_fromUtf8(""))
        self.cbTubeForm.addItem(_fromUtf8(""))
        self.tubeSettingsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbTubeForm)
        self.lblTubeLength = QtGui.QLabel(self.tabRecording1)
        self.lblTubeLength.setObjectName(_fromUtf8("lblTubeLength"))
        self.tubeSettingsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblTubeLength)
        self.editTubeLength = QtGui.QLineEdit(self.tabRecording1)
        self.editTubeLength.setObjectName(_fromUtf8("editTubeLength"))
        self.tubeSettingsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.editTubeLength)
        self.lblTubeDiameter = QtGui.QLabel(self.tabRecording1)
        self.lblTubeDiameter.setObjectName(_fromUtf8("lblTubeDiameter"))
        self.tubeSettingsLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblTubeDiameter)
        self.editTubeDiameter = QtGui.QLineEdit(self.tabRecording1)
        self.editTubeDiameter.setObjectName(_fromUtf8("editTubeDiameter"))
        self.tubeSettingsLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.editTubeDiameter)
        self.lblMicDistanceSmall = QtGui.QLabel(self.tabRecording1)
        self.lblMicDistanceSmall.setObjectName(_fromUtf8("lblMicDistanceSmall"))
        self.tubeSettingsLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblMicDistanceSmall)
        self.editMicDistanceSmall = QtGui.QLineEdit(self.tabRecording1)
        self.editMicDistanceSmall.setObjectName(_fromUtf8("editMicDistanceSmall"))
        self.tubeSettingsLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.editMicDistanceSmall)
        self.lblMicDistanceWide = QtGui.QLabel(self.tabRecording1)
        self.lblMicDistanceWide.setObjectName(_fromUtf8("lblMicDistanceWide"))
        self.tubeSettingsLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblMicDistanceWide)
        self.editMicDistanceWide = QtGui.QLineEdit(self.tabRecording1)
        self.editMicDistanceWide.setObjectName(_fromUtf8("editMicDistanceWide"))
        self.tubeSettingsLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.editMicDistanceWide)
        self.lblTubeSettings = QtGui.QLabel(self.tabRecording1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTubeSettings.setFont(font)
        self.lblTubeSettings.setObjectName(_fromUtf8("lblTubeSettings"))
        self.tubeSettingsLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.lblTubeSettings)
        self.verticalLayout_2.addLayout(self.tubeSettingsLayout)
        self.tabWidget.addTab(self.tabRecording1, _fromUtf8(""))
        self.tabFFT = QtGui.QWidget()
        self.tabFFT.setObjectName(_fromUtf8("tabFFT"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabFFT)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.FFTSettingsLayout = QtGui.QFormLayout()
        self.FFTSettingsLayout.setObjectName(_fromUtf8("FFTSettingsLayout"))
        self.lblFFTWindow = QtGui.QLabel(self.tabFFT)
        self.lblFFTWindow.setObjectName(_fromUtf8("lblFFTWindow"))
        self.FFTSettingsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFFTWindow)
        self.cbFFTWindow = QtGui.QComboBox(self.tabFFT)
        self.cbFFTWindow.setObjectName(_fromUtf8("cbFFTWindow"))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.FFTSettingsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbFFTWindow)
        self.lblFFTResolution = QtGui.QLabel(self.tabFFT)
        self.lblFFTResolution.setObjectName(_fromUtf8("lblFFTResolution"))
        self.FFTSettingsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblFFTResolution)
        self.editFFTResoultion = QtGui.QLineEdit(self.tabFFT)
        self.editFFTResoultion.setObjectName(_fromUtf8("editFFTResoultion"))
        self.FFTSettingsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.editFFTResoultion)
        self.lblFFTSettings = QtGui.QLabel(self.tabFFT)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFFTSettings.setFont(font)
        self.lblFFTSettings.setObjectName(_fromUtf8("lblFFTSettings"))
        self.FFTSettingsLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.lblFFTSettings)
        self.verticalLayout_4.addLayout(self.FFTSettingsLayout)
        self.tabWidget.addTab(self.tabFFT, _fromUtf8(""))
        self.tabSignal = QtGui.QWidget()
        self.tabSignal.setObjectName(_fromUtf8("tabSignal"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabSignal)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.signalSettingsLayout = QtGui.QFormLayout()
        self.signalSettingsLayout.setObjectName(_fromUtf8("signalSettingsLayout"))
        self.lblSignalSettings = QtGui.QLabel(self.tabSignal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSignalSettings.setFont(font)
        self.lblSignalSettings.setObjectName(_fromUtf8("lblSignalSettings"))
        self.signalSettingsLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblSignalSettings)
        self.lblSignalType = QtGui.QLabel(self.tabSignal)
        self.lblSignalType.setObjectName(_fromUtf8("lblSignalType"))
        self.signalSettingsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblSignalType)
        self.cbSignalType = QtGui.QComboBox(self.tabSignal)
        self.cbSignalType.setObjectName(_fromUtf8("cbSignalType"))
        self.cbSignalType.addItem(_fromUtf8(""))
        self.cbSignalType.addItem(_fromUtf8(""))
        self.cbSignalType.addItem(_fromUtf8(""))
        self.signalSettingsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbSignalType)
        self.lblSignalDevice = QtGui.QLabel(self.tabSignal)
        self.lblSignalDevice.setObjectName(_fromUtf8("lblSignalDevice"))
        self.signalSettingsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblSignalDevice)
        self.cbSignalDevice = QtGui.QComboBox(self.tabSignal)
        self.cbSignalDevice.setObjectName(_fromUtf8("cbSignalDevice"))
        self.signalSettingsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbSignalDevice)
        self.verticalLayout_5.addLayout(self.signalSettingsLayout)
        self.tabWidget.addTab(self.tabSignal, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAbort = QtGui.QPushButton(hwSettingsDialog)
        self.btnAbort.setObjectName(_fromUtf8("btnAbort"))
        self.horizontalLayout.addWidget(self.btnAbort)
        self.btnLoadHwSettings = QtGui.QPushButton(hwSettingsDialog)
        self.btnLoadHwSettings.setObjectName(_fromUtf8("btnLoadHwSettings"))
        self.horizontalLayout.addWidget(self.btnLoadHwSettings)
        self.btnSaveHwSettings = QtGui.QPushButton(hwSettingsDialog)
        self.btnSaveHwSettings.setObjectName(_fromUtf8("btnSaveHwSettings"))
        self.horizontalLayout.addWidget(self.btnSaveHwSettings)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(hwSettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(hwSettingsDialog)

    def retranslateUi(self, hwSettingsDialog):
        hwSettingsDialog.setWindowTitle(_translate("hwSettingsDialog", "Hardware-Einstellungen", None))
        self.lblRecordingSettings.setText(_translate("hwSettingsDialog", "Aufnahme", None))
        self.lblRecMic1.setText(_translate("hwSettingsDialog", "Mikrofon 1", None))
        self.lblRecMic2.setText(_translate("hwSettingsDialog", "Mikrofon 2", None))
        self.lblRecSamplFreq.setText(_translate("hwSettingsDialog", "Sampling Freq.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRecording), _translate("hwSettingsDialog", "Aufnahme", None))
        self.lblTubeForm.setText(_translate("hwSettingsDialog", "Form", None))
        self.cbTubeForm.setItemText(0, _translate("hwSettingsDialog", "Rund", None))
        self.cbTubeForm.setItemText(1, _translate("hwSettingsDialog", "Quadratisch", None))
        self.lblTubeLength.setText(_translate("hwSettingsDialog", "Länge in m", None))
        self.editTubeLength.setText(_translate("hwSettingsDialog", "sdf", None))
        self.lblTubeDiameter.setText(_translate("hwSettingsDialog", "Seitenlänge/Durchmesser in m", None))
        self.editTubeDiameter.setText(_translate("hwSettingsDialog", "sdf", None))
        self.lblMicDistanceSmall.setText(_translate("hwSettingsDialog", "Mikrofonabstand (eng) in m", None))
        self.editMicDistanceSmall.setText(_translate("hwSettingsDialog", "sdf", None))
        self.lblMicDistanceWide.setText(_translate("hwSettingsDialog", "Mikrofonabstand (weit) in m", None))
        self.editMicDistanceWide.setText(_translate("hwSettingsDialog", "sdf", None))
        self.lblTubeSettings.setText(_translate("hwSettingsDialog", "Rohr", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRecording1), _translate("hwSettingsDialog", "Rohr", None))
        self.lblFFTWindow.setText(_translate("hwSettingsDialog", "Fensterfunktion", None))
        self.cbFFTWindow.setItemText(0, _translate("hwSettingsDialog", "Rechteck", None))
        self.cbFFTWindow.setItemText(1, _translate("hwSettingsDialog", "Hamming", None))
        self.cbFFTWindow.setItemText(2, _translate("hwSettingsDialog", "Hanning", None))
        self.cbFFTWindow.setItemText(3, _translate("hwSettingsDialog", "Bartlett (Triangular)", None))
        self.cbFFTWindow.setItemText(4, _translate("hwSettingsDialog", "Blackman 3-term", None))
        self.cbFFTWindow.setItemText(5, _translate("hwSettingsDialog", "Blackman-Harris 4-term", None))
        self.cbFFTWindow.setItemText(6, _translate("hwSettingsDialog", "Blackman-Harris 7-Term", None))
        self.cbFFTWindow.setItemText(7, _translate("hwSettingsDialog", "Tuckey (alpha = 0.66)", None))
        self.cbFFTWindow.setItemText(8, _translate("hwSettingsDialog", "Sinus (halb-sinus Fenster)", None))
        self.lblFFTResolution.setText(_translate("hwSettingsDialog", "Auflösung in Hz", None))
        self.lblFFTSettings.setText(_translate("hwSettingsDialog", "FFT", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFFT), _translate("hwSettingsDialog", "FFT", None))
        self.lblSignalSettings.setText(_translate("hwSettingsDialog", "Signal", None))
        self.lblSignalType.setText(_translate("hwSettingsDialog", "Signaltyp", None))
        self.cbSignalType.setItemText(0, _translate("hwSettingsDialog", "Multisinus Crest 96", None))
        self.cbSignalType.setItemText(1, _translate("hwSettingsDialog", "Multisinus Crest 44", None))
        self.cbSignalType.setItemText(2, _translate("hwSettingsDialog", "Weißes Rauschen", None))
        self.lblSignalDevice.setText(_translate("hwSettingsDialog", "Gerät", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSignal), _translate("hwSettingsDialog", "Signal", None))
        self.btnAbort.setText(_translate("hwSettingsDialog", "Abbrechen", None))
        self.btnLoadHwSettings.setText(_translate("hwSettingsDialog", "Laden", None))
        self.btnSaveHwSettings.setText(_translate("hwSettingsDialog", "Speichern", None))

