# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Wed Aug  5 09:24:10 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1172, 708)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.graphSelectionLayout = QtGui.QVBoxLayout()
        self.graphSelectionLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.graphSelectionLayout.setObjectName(_fromUtf8("graphSelectionLayout"))
        self.lblProject = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProject.setFont(font)
        self.lblProject.setObjectName(_fromUtf8("lblProject"))
        self.graphSelectionLayout.addWidget(self.lblProject)
        self.listProjectMeasurements = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listProjectMeasurements.sizePolicy().hasHeightForWidth())
        self.listProjectMeasurements.setSizePolicy(sizePolicy)
        self.listProjectMeasurements.setObjectName(_fromUtf8("listProjectMeasurements"))
        self.graphSelectionLayout.addWidget(self.listProjectMeasurements)
        self.btnProjectClearSelection = QtGui.QPushButton(self.centralwidget)
        self.btnProjectClearSelection.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnProjectClearSelection.sizePolicy().hasHeightForWidth())
        self.btnProjectClearSelection.setSizePolicy(sizePolicy)
        self.btnProjectClearSelection.setObjectName(_fromUtf8("btnProjectClearSelection"))
        self.graphSelectionLayout.addWidget(self.btnProjectClearSelection)
        self.lblMeasureParam = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblMeasureParam.setFont(font)
        self.lblMeasureParam.setObjectName(_fromUtf8("lblMeasureParam"))
        self.graphSelectionLayout.addWidget(self.lblMeasureParam)
        self.listMeasurementParameter = QtGui.QListWidget(self.centralwidget)
        self.listMeasurementParameter.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listMeasurementParameter.sizePolicy().hasHeightForWidth())
        self.listMeasurementParameter.setSizePolicy(sizePolicy)
        self.listMeasurementParameter.setObjectName(_fromUtf8("listMeasurementParameter"))
        self.graphSelectionLayout.addWidget(self.listMeasurementParameter)
        self.btnMeasureParamClearSelection = QtGui.QPushButton(self.centralwidget)
        self.btnMeasureParamClearSelection.setEnabled(False)
        self.btnMeasureParamClearSelection.setObjectName(_fromUtf8("btnMeasureParamClearSelection"))
        self.graphSelectionLayout.addWidget(self.btnMeasureParamClearSelection)
        self.horizontalLayout_2.addLayout(self.graphSelectionLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblLowerDisplayedFrequency = QtGui.QLabel(self.centralwidget)
        self.lblLowerDisplayedFrequency.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLowerDisplayedFrequency.setObjectName(_fromUtf8("lblLowerDisplayedFrequency"))
        self.horizontalLayout.addWidget(self.lblLowerDisplayedFrequency)
        self.dsbLowerDisplayedFrequency = QtGui.QDoubleSpinBox(self.centralwidget)
        self.dsbLowerDisplayedFrequency.setEnabled(False)
        self.dsbLowerDisplayedFrequency.setObjectName(_fromUtf8("dsbLowerDisplayedFrequency"))
        self.horizontalLayout.addWidget(self.dsbLowerDisplayedFrequency)
        self.lblUpperDisplayedFrequency = QtGui.QLabel(self.centralwidget)
        self.lblUpperDisplayedFrequency.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUpperDisplayedFrequency.setObjectName(_fromUtf8("lblUpperDisplayedFrequency"))
        self.horizontalLayout.addWidget(self.lblUpperDisplayedFrequency)
        self.dsbUpperDisplayedFrequency = QtGui.QDoubleSpinBox(self.centralwidget)
        self.dsbUpperDisplayedFrequency.setEnabled(False)
        self.dsbUpperDisplayedFrequency.setObjectName(_fromUtf8("dsbUpperDisplayedFrequency"))
        self.horizontalLayout.addWidget(self.dsbUpperDisplayedFrequency)
        self.btnApplyFrequencyRange = QtGui.QPushButton(self.centralwidget)
        self.btnApplyFrequencyRange.setEnabled(False)
        self.btnApplyFrequencyRange.setObjectName(_fromUtf8("btnApplyFrequencyRange"))
        self.horizontalLayout.addWidget(self.btnApplyFrequencyRange)
        self.btnRefreshSelection = QtGui.QPushButton(self.centralwidget)
        self.btnRefreshSelection.setEnabled(False)
        self.btnRefreshSelection.setObjectName(_fromUtf8("btnRefreshSelection"))
        self.horizontalLayout.addWidget(self.btnRefreshSelection)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.qwtPlot = QwtPlot(self.centralwidget)
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.verticalLayout.addWidget(self.qwtPlot)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1172, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuAnalysis = QtGui.QMenu(self.menubar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuTube = QtGui.QMenu(self.menubar)
        self.menuTube.setObjectName(_fromUtf8("menuTube"))
        self.menuMeasurement = QtGui.QMenu(self.menubar)
        self.menuMeasurement.setObjectName(_fromUtf8("menuMeasurement"))
        self.menuGraph = QtGui.QMenu(self.menubar)
        self.menuGraph.setObjectName(_fromUtf8("menuGraph"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionPegel_Einstellen = QtGui.QAction(MainWindow)
        self.actionPegel_Einstellen.setObjectName(_fromUtf8("actionPegel_Einstellen"))
        self.actionKorrekturfunktion_Bestimmen = QtGui.QAction(MainWindow)
        self.actionKorrekturfunktion_Bestimmen.setObjectName(_fromUtf8("actionKorrekturfunktion_Bestimmen"))
        self.actionEinstellungen = QtGui.QAction(MainWindow)
        self.actionEinstellungen.setObjectName(_fromUtf8("actionEinstellungen"))
        self.actionNeue_Messreihe = QtGui.QAction(MainWindow)
        self.actionNeue_Messreihe.setObjectName(_fromUtf8("actionNeue_Messreihe"))
        self.actionMessreihe_ffnen = QtGui.QAction(MainWindow)
        self.actionMessreihe_ffnen.setObjectName(_fromUtf8("actionMessreihe_ffnen"))
        self.actionMessreihe_Speichern = QtGui.QAction(MainWindow)
        self.actionMessreihe_Speichern.setObjectName(_fromUtf8("actionMessreihe_Speichern"))
        self.actionMessreihe_speichern_unter = QtGui.QAction(MainWindow)
        self.actionMessreihe_speichern_unter.setObjectName(_fromUtf8("actionMessreihe_speichern_unter"))
        self.actionMessreihe_exportieren = QtGui.QAction(MainWindow)
        self.actionMessreihe_exportieren.setObjectName(_fromUtf8("actionMessreihe_exportieren"))
        self.actionExitApp = QtGui.QAction(MainWindow)
        self.actionExitApp.setObjectName(_fromUtf8("actionExitApp"))
        self.actionProjekt_Einstellungen = QtGui.QAction(MainWindow)
        self.actionProjekt_Einstellungen.setObjectName(_fromUtf8("actionProjekt_Einstellungen"))
        self.actionHardware_Assistent = QtGui.QAction(MainWindow)
        self.actionHardware_Assistent.setObjectName(_fromUtf8("actionHardware_Assistent"))
        self.actionMessreihen_Assistent = QtGui.QAction(MainWindow)
        self.actionMessreihen_Assistent.setObjectName(_fromUtf8("actionMessreihen_Assistent"))
        self.actionGetGrainImpedanceModelParameters = QtGui.QAction(MainWindow)
        self.actionGetGrainImpedanceModelParameters.setObjectName(_fromUtf8("actionGetGrainImpedanceModelParameters"))
        self.actionNewTube = QtGui.QAction(MainWindow)
        self.actionNewTube.setObjectName(_fromUtf8("actionNewTube"))
        self.actionLoadTube = QtGui.QAction(MainWindow)
        self.actionLoadTube.setObjectName(_fromUtf8("actionLoadTube"))
        self.actionNewProject = QtGui.QAction(MainWindow)
        self.actionNewProject.setObjectName(_fromUtf8("actionNewProject"))
        self.actionLoadProject = QtGui.QAction(MainWindow)
        self.actionLoadProject.setObjectName(_fromUtf8("actionLoadProject"))
        self.actionSaveProject = QtGui.QAction(MainWindow)
        self.actionSaveProject.setEnabled(False)
        self.actionSaveProject.setObjectName(_fromUtf8("actionSaveProject"))
        self.actionSaveTube = QtGui.QAction(MainWindow)
        self.actionSaveTube.setEnabled(False)
        self.actionSaveTube.setObjectName(_fromUtf8("actionSaveTube"))
        self.actionNewMeasurement = QtGui.QAction(MainWindow)
        self.actionNewMeasurement.setEnabled(False)
        self.actionNewMeasurement.setObjectName(_fromUtf8("actionNewMeasurement"))
        self.actionRemoveMeasurement = QtGui.QAction(MainWindow)
        self.actionRemoveMeasurement.setEnabled(False)
        self.actionRemoveMeasurement.setObjectName(_fromUtf8("actionRemoveMeasurement"))
        self.actionExportMeasurement = QtGui.QAction(MainWindow)
        self.actionExportMeasurement.setEnabled(False)
        self.actionExportMeasurement.setObjectName(_fromUtf8("actionExportMeasurement"))
        self.actionMeasureCorrFunc = QtGui.QAction(MainWindow)
        self.actionMeasureCorrFunc.setEnabled(False)
        self.actionMeasureCorrFunc.setObjectName(_fromUtf8("actionMeasureCorrFunc"))
        self.actionConfigureLevel = QtGui.QAction(MainWindow)
        self.actionConfigureLevel.setEnabled(False)
        self.actionConfigureLevel.setObjectName(_fromUtf8("actionConfigureLevel"))
        self.actionLinear = QtGui.QAction(MainWindow)
        self.actionLinear.setCheckable(True)
        self.actionLinear.setChecked(True)
        self.actionLinear.setObjectName(_fromUtf8("actionLinear"))
        self.actionLogarithmic = QtGui.QAction(MainWindow)
        self.actionLogarithmic.setCheckable(True)
        self.actionLogarithmic.setChecked(False)
        self.actionLogarithmic.setObjectName(_fromUtf8("actionLogarithmic"))
        self.actionMagintudeAngle = QtGui.QAction(MainWindow)
        self.actionMagintudeAngle.setCheckable(True)
        self.actionMagintudeAngle.setChecked(True)
        self.actionMagintudeAngle.setObjectName(_fromUtf8("actionMagintudeAngle"))
        self.actionRealImaginary = QtGui.QAction(MainWindow)
        self.actionRealImaginary.setCheckable(True)
        self.actionRealImaginary.setObjectName(_fromUtf8("actionRealImaginary"))
        self.actionExportAsPicture = QtGui.QAction(MainWindow)
        self.actionExportAsPicture.setObjectName(_fromUtf8("actionExportAsPicture"))
        self.actionExportProject = QtGui.QAction(MainWindow)
        self.actionExportProject.setEnabled(False)
        self.actionExportProject.setObjectName(_fromUtf8("actionExportProject"))
        self.actionGraphSettings = QtGui.QAction(MainWindow)
        self.actionGraphSettings.setObjectName(_fromUtf8("actionGraphSettings"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExitApp)
        self.menuAnalysis.addAction(self.actionGetGrainImpedanceModelParameters)
        self.menuProject.addAction(self.actionNewProject)
        self.menuProject.addAction(self.actionLoadProject)
        self.menuProject.addAction(self.actionSaveProject)
        self.menuProject.addAction(self.actionMeasureCorrFunc)
        self.menuProject.addAction(self.actionExportProject)
        self.menuTube.addAction(self.actionNewTube)
        self.menuTube.addAction(self.actionLoadTube)
        self.menuTube.addAction(self.actionSaveTube)
        self.menuTube.addSeparator()
        self.menuTube.addAction(self.actionConfigureLevel)
        self.menuMeasurement.addAction(self.actionNewMeasurement)
        self.menuMeasurement.addAction(self.actionRemoveMeasurement)
        self.menuMeasurement.addAction(self.actionExportMeasurement)
        self.menuGraph.addAction(self.actionGraphSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTube.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuMeasurement.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        self.listMeasurementParameter.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ImpedanceTube Control Software ITCS", None))
        self.lblProject.setText(_translate("MainWindow", "Projekt", None))
        self.btnProjectClearSelection.setText(_translate("MainWindow", "Auswahl Aufheben", None))
        self.lblMeasureParam.setText(_translate("MainWindow", "Messungs-Parameter", None))
        self.btnMeasureParamClearSelection.setText(_translate("MainWindow", "Auswahl Aufheben", None))
        self.lblLowerDisplayedFrequency.setText(_translate("MainWindow", "Untere angezeigte Frequenz:", None))
        self.lblUpperDisplayedFrequency.setText(_translate("MainWindow", "Obere angezeigte Frequenz:", None))
        self.btnApplyFrequencyRange.setText(_translate("MainWindow", "Auswahl anwenden", None))
        self.btnRefreshSelection.setText(_translate("MainWindow", "Auswahl aktualisieren", None))
        self.menuFile.setTitle(_translate("MainWindow", "Datei", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analyse", None))
        self.menuProject.setTitle(_translate("MainWindow", "Projekt", None))
        self.menuTube.setTitle(_translate("MainWindow", "Messrohr", None))
        self.menuMeasurement.setTitle(_translate("MainWindow", "Messung", None))
        self.menuGraph.setTitle(_translate("MainWindow", "Graph", None))
        self.actionPegel_Einstellen.setText(_translate("MainWindow", "Pegel einstellen", None))
        self.actionKorrekturfunktion_Bestimmen.setText(_translate("MainWindow", "Kalibrieren", None))
        self.actionEinstellungen.setText(_translate("MainWindow", "Hardware-Einstellungen", None))
        self.actionNeue_Messreihe.setText(_translate("MainWindow", "Neue Messreihe", None))
        self.actionMessreihe_ffnen.setText(_translate("MainWindow", "Messreihe öffnen", None))
        self.actionMessreihe_Speichern.setText(_translate("MainWindow", "Messreihe speichern", None))
        self.actionMessreihe_speichern_unter.setText(_translate("MainWindow", "Messreihe speichern unter...", None))
        self.actionMessreihe_exportieren.setText(_translate("MainWindow", "Messreihe exportieren", None))
        self.actionExitApp.setText(_translate("MainWindow", "Programm beenden", None))
        self.actionProjekt_Einstellungen.setText(_translate("MainWindow", "Messreihen-Einstellungen", None))
        self.actionHardware_Assistent.setText(_translate("MainWindow", "Hardware-Assistent", None))
        self.actionMessreihen_Assistent.setText(_translate("MainWindow", "Messreihen-Assistent", None))
        self.actionGetGrainImpedanceModelParameters.setText(_translate("MainWindow", "Getreide-Modellparameter Bestimmen", None))
        self.actionNewTube.setText(_translate("MainWindow", "Neues Messrohr...", None))
        self.actionLoadTube.setText(_translate("MainWindow", "Messrohr laden", None))
        self.actionNewProject.setText(_translate("MainWindow", "Neues Projekt", None))
        self.actionLoadProject.setText(_translate("MainWindow", "Projekt laden", None))
        self.actionSaveProject.setText(_translate("MainWindow", "Projekt speichern", None))
        self.actionSaveTube.setText(_translate("MainWindow", "Messrohr speichern", None))
        self.actionNewMeasurement.setText(_translate("MainWindow", "Neue Messung", None))
        self.actionRemoveMeasurement.setText(_translate("MainWindow", "Messung entfernen", None))
        self.actionExportMeasurement.setText(_translate("MainWindow", "Messung exportieren", None))
        self.actionMeasureCorrFunc.setText(_translate("MainWindow", "Korrekturfunktion Messen", None))
        self.actionConfigureLevel.setText(_translate("MainWindow", "Pegel einstellen", None))
        self.actionLinear.setText(_translate("MainWindow", "Linear", None))
        self.actionLogarithmic.setText(_translate("MainWindow", "Logarithmisch", None))
        self.actionMagintudeAngle.setText(_translate("MainWindow", "Betrag/Winkel", None))
        self.actionRealImaginary.setText(_translate("MainWindow", "Real/Imaginär", None))
        self.actionExportAsPicture.setText(_translate("MainWindow", "Als Grafik exportieren", None))
        self.actionExportProject.setText(_translate("MainWindow", "Exportieren", None))
        self.actionGraphSettings.setText(_translate("MainWindow", "Einstellungen", None))

from PyQt4.Qwt5 import QwtPlot