# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_settings.ui'
#
# Created: Wed Aug  5 09:24:09 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_projectSettingsDialog(object):
    def setupUi(self, projectSettingsDialog):
        projectSettingsDialog.setObjectName(_fromUtf8("projectSettingsDialog"))
        projectSettingsDialog.resize(631, 358)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(projectSettingsDialog)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.projectDataLayout = QtGui.QFormLayout()
        self.projectDataLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.projectDataLayout.setObjectName(_fromUtf8("projectDataLayout"))
        self.lblProjectName = QtGui.QLabel(projectSettingsDialog)
        self.lblProjectName.setObjectName(_fromUtf8("lblProjectName"))
        self.projectDataLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblProjectName)
        self.editProjectName = QtGui.QLineEdit(projectSettingsDialog)
        self.editProjectName.setObjectName(_fromUtf8("editProjectName"))
        self.projectDataLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.editProjectName)
        self.lblProjectDate = QtGui.QLabel(projectSettingsDialog)
        self.lblProjectDate.setObjectName(_fromUtf8("lblProjectDate"))
        self.projectDataLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblProjectDate)
        self.lblProjectComment = QtGui.QLabel(projectSettingsDialog)
        self.lblProjectComment.setObjectName(_fromUtf8("lblProjectComment"))
        self.projectDataLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblProjectComment)
        self.textProjectComment = QtGui.QPlainTextEdit(projectSettingsDialog)
        self.textProjectComment.setObjectName(_fromUtf8("textProjectComment"))
        self.projectDataLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.textProjectComment)
        self.lblProjectDataSettings = QtGui.QLabel(projectSettingsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProjectDataSettings.setFont(font)
        self.lblProjectDataSettings.setObjectName(_fromUtf8("lblProjectDataSettings"))
        self.projectDataLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.lblProjectDataSettings)
        self.dateProjectDate = QtGui.QDateEdit(projectSettingsDialog)
        self.dateProjectDate.setObjectName(_fromUtf8("dateProjectDate"))
        self.projectDataLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dateProjectDate)
        self.verticalLayout_2.addLayout(self.projectDataLayout)
        self.envirSettingsLayout = QtGui.QFormLayout()
        self.envirSettingsLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.envirSettingsLayout.setObjectName(_fromUtf8("envirSettingsLayout"))
        self.lblEnvirPressure = QtGui.QLabel(projectSettingsDialog)
        self.lblEnvirPressure.setObjectName(_fromUtf8("lblEnvirPressure"))
        self.envirSettingsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblEnvirPressure)
        self.editEnvirPressure = QtGui.QLineEdit(projectSettingsDialog)
        self.editEnvirPressure.setObjectName(_fromUtf8("editEnvirPressure"))
        self.envirSettingsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.editEnvirPressure)
        self.lblEnvirRelHumidity = QtGui.QLabel(projectSettingsDialog)
        self.lblEnvirRelHumidity.setObjectName(_fromUtf8("lblEnvirRelHumidity"))
        self.envirSettingsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblEnvirRelHumidity)
        self.editEnvirRelHumidity = QtGui.QLineEdit(projectSettingsDialog)
        self.editEnvirRelHumidity.setObjectName(_fromUtf8("editEnvirRelHumidity"))
        self.envirSettingsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.editEnvirRelHumidity)
        self.lblEnvirTemp = QtGui.QLabel(projectSettingsDialog)
        self.lblEnvirTemp.setObjectName(_fromUtf8("lblEnvirTemp"))
        self.envirSettingsLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblEnvirTemp)
        self.editEnvirTemp = QtGui.QLineEdit(projectSettingsDialog)
        self.editEnvirTemp.setObjectName(_fromUtf8("editEnvirTemp"))
        self.envirSettingsLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.editEnvirTemp)
        self.lblEnvirSettings = QtGui.QLabel(projectSettingsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEnvirSettings.setFont(font)
        self.lblEnvirSettings.setObjectName(_fromUtf8("lblEnvirSettings"))
        self.envirSettingsLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.lblEnvirSettings)
        self.verticalLayout_2.addLayout(self.envirSettingsLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.materialSettingsLayout = QtGui.QFormLayout()
        self.materialSettingsLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.materialSettingsLayout.setObjectName(_fromUtf8("materialSettingsLayout"))
        self.lblMaterial = QtGui.QLabel(projectSettingsDialog)
        self.lblMaterial.setObjectName(_fromUtf8("lblMaterial"))
        self.materialSettingsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblMaterial)
        self.editMaterial = QtGui.QLineEdit(projectSettingsDialog)
        self.editMaterial.setObjectName(_fromUtf8("editMaterial"))
        self.materialSettingsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.editMaterial)
        self.lblMaterialDepth = QtGui.QLabel(projectSettingsDialog)
        self.lblMaterialDepth.setObjectName(_fromUtf8("lblMaterialDepth"))
        self.materialSettingsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblMaterialDepth)
        self.editMaterialWidth = QtGui.QLineEdit(projectSettingsDialog)
        self.editMaterialWidth.setObjectName(_fromUtf8("editMaterialWidth"))
        self.materialSettingsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.editMaterialWidth)
        self.lblMaterialCleanliness = QtGui.QLabel(projectSettingsDialog)
        self.lblMaterialCleanliness.setObjectName(_fromUtf8("lblMaterialCleanliness"))
        self.materialSettingsLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblMaterialCleanliness)
        self.editMaterialCleanliness = QtGui.QLineEdit(projectSettingsDialog)
        self.editMaterialCleanliness.setObjectName(_fromUtf8("editMaterialCleanliness"))
        self.materialSettingsLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.editMaterialCleanliness)
        self.lblMaterialGrubContent = QtGui.QLabel(projectSettingsDialog)
        self.lblMaterialGrubContent.setObjectName(_fromUtf8("lblMaterialGrubContent"))
        self.materialSettingsLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblMaterialGrubContent)
        self.editMaterialGrubContent = QtGui.QLineEdit(projectSettingsDialog)
        self.editMaterialGrubContent.setObjectName(_fromUtf8("editMaterialGrubContent"))
        self.materialSettingsLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.editMaterialGrubContent)
        self.lblMaterialTSW = QtGui.QLabel(projectSettingsDialog)
        self.lblMaterialTSW.setObjectName(_fromUtf8("lblMaterialTSW"))
        self.materialSettingsLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblMaterialTSW)
        self.editMaterialTSW = QtGui.QLineEdit(projectSettingsDialog)
        self.editMaterialTSW.setObjectName(_fromUtf8("editMaterialTSW"))
        self.materialSettingsLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.editMaterialTSW)
        self.lblMaterialSettings = QtGui.QLabel(projectSettingsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblMaterialSettings.setFont(font)
        self.lblMaterialSettings.setObjectName(_fromUtf8("lblMaterialSettings"))
        self.materialSettingsLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.lblMaterialSettings)
        self.verticalLayout.addLayout(self.materialSettingsLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(projectSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(projectSettingsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), projectSettingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), projectSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(projectSettingsDialog)

    def retranslateUi(self, projectSettingsDialog):
        projectSettingsDialog.setWindowTitle(_translate("projectSettingsDialog", "Projekt-Einstellungen", None))
        self.lblProjectName.setText(_translate("projectSettingsDialog", "Projektname", None))
        self.lblProjectDate.setText(_translate("projectSettingsDialog", "Datum", None))
        self.lblProjectComment.setText(_translate("projectSettingsDialog", "Kommentar", None))
        self.lblProjectDataSettings.setText(_translate("projectSettingsDialog", "Projektdaten", None))
        self.lblEnvirPressure.setText(_translate("projectSettingsDialog", "Luftdruck", None))
        self.lblEnvirRelHumidity.setText(_translate("projectSettingsDialog", "rel. Luftfeuchte", None))
        self.lblEnvirTemp.setText(_translate("projectSettingsDialog", "Temperatur", None))
        self.lblEnvirSettings.setText(_translate("projectSettingsDialog", "Umgebungsdaten", None))
        self.lblMaterial.setText(_translate("projectSettingsDialog", "Material", None))
        self.lblMaterialDepth.setText(_translate("projectSettingsDialog", "Materialstärke", None))
        self.lblMaterialCleanliness.setText(_translate("projectSettingsDialog", "Reinigungsgrad", None))
        self.lblMaterialGrubContent.setText(_translate("projectSettingsDialog", "Anteil Fraßmehl", None))
        self.lblMaterialTSW.setText(_translate("projectSettingsDialog", "TKG", None))
        self.lblMaterialSettings.setText(_translate("projectSettingsDialog", "Material Information", None))

