# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_wizard.ui'
#
# Created: Wed Aug  5 09:24:10 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_newProjectWizard(object):
    def setupUi(self, newProjectWizard):
        newProjectWizard.setObjectName(_fromUtf8("newProjectWizard"))
        newProjectWizard.resize(453, 340)
        self.wpProjectData = QtGui.QWizardPage()
        self.wpProjectData.setSubTitle(_fromUtf8(""))
        self.wpProjectData.setObjectName(_fromUtf8("wpProjectData"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wpProjectData)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widProjectData = QtGui.QWidget(self.wpProjectData)
        self.widProjectData.setObjectName(_fromUtf8("widProjectData"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widProjectData)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblName = QtGui.QLabel(self.widProjectData)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblName)
        self.editName = QtGui.QLineEdit(self.widProjectData)
        self.editName.setObjectName(_fromUtf8("editName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.editName)
        self.lblDate = QtGui.QLabel(self.widProjectData)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblDate)
        self.deDate = QtGui.QDateEdit(self.widProjectData)
        self.deDate.setCalendarPopup(True)
        self.deDate.setObjectName(_fromUtf8("deDate"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.deDate)
        self.lblComment = QtGui.QLabel(self.widProjectData)
        self.lblComment.setObjectName(_fromUtf8("lblComment"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblComment)
        self.teComment = QtGui.QTextEdit(self.widProjectData)
        self.teComment.setObjectName(_fromUtf8("teComment"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.teComment)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.widProjectData)
        newProjectWizard.addPage(self.wpProjectData)
        self.wpMaterialParameters = QtGui.QWizardPage()
        self.wpMaterialParameters.setObjectName(_fromUtf8("wpMaterialParameters"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.wpMaterialParameters)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widMaterialParameters = QtGui.QWidget(self.wpMaterialParameters)
        self.widMaterialParameters.setObjectName(_fromUtf8("widMaterialParameters"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widMaterialParameters)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblMaterial = QtGui.QLabel(self.widMaterialParameters)
        self.lblMaterial.setObjectName(_fromUtf8("lblMaterial"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblMaterial)
        self.editMaterial = QtGui.QLineEdit(self.widMaterialParameters)
        self.editMaterial.setObjectName(_fromUtf8("editMaterial"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.editMaterial)
        self.lblMaterialDepth = QtGui.QLabel(self.widMaterialParameters)
        self.lblMaterialDepth.setObjectName(_fromUtf8("lblMaterialDepth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblMaterialDepth)
        self.lblDegreeOfCleaning = QtGui.QLabel(self.widMaterialParameters)
        self.lblDegreeOfCleaning.setObjectName(_fromUtf8("lblDegreeOfCleaning"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblDegreeOfCleaning)
        self.lblAmountOfScrub = QtGui.QLabel(self.widMaterialParameters)
        self.lblAmountOfScrub.setObjectName(_fromUtf8("lblAmountOfScrub"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblAmountOfScrub)
        self.lblTSeedWeight = QtGui.QLabel(self.widMaterialParameters)
        self.lblTSeedWeight.setObjectName(_fromUtf8("lblTSeedWeight"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblTSeedWeight)
        self.dsbAmountOfScrub = QtGui.QDoubleSpinBox(self.widMaterialParameters)
        self.dsbAmountOfScrub.setDecimals(1)
        self.dsbAmountOfScrub.setObjectName(_fromUtf8("dsbAmountOfScrub"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.dsbAmountOfScrub)
        self.dsbDegreeOfCleaning = QtGui.QDoubleSpinBox(self.widMaterialParameters)
        self.dsbDegreeOfCleaning.setDecimals(1)
        self.dsbDegreeOfCleaning.setMaximum(100.0)
        self.dsbDegreeOfCleaning.setSingleStep(0.1)
        self.dsbDegreeOfCleaning.setObjectName(_fromUtf8("dsbDegreeOfCleaning"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.dsbDegreeOfCleaning)
        self.dsbMaterialThickness = QtGui.QDoubleSpinBox(self.widMaterialParameters)
        self.dsbMaterialThickness.setDecimals(1)
        self.dsbMaterialThickness.setMaximum(1000.0)
        self.dsbMaterialThickness.setObjectName(_fromUtf8("dsbMaterialThickness"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.dsbMaterialThickness)
        self.dsbThousandSeedWeight = QtGui.QDoubleSpinBox(self.widMaterialParameters)
        self.dsbThousandSeedWeight.setMaximum(1000.0)
        self.dsbThousandSeedWeight.setObjectName(_fromUtf8("dsbThousandSeedWeight"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.dsbThousandSeedWeight)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_3.addWidget(self.widMaterialParameters)
        newProjectWizard.addPage(self.wpMaterialParameters)
        self.wpEnvironmentParameters = QtGui.QWizardPage()
        self.wpEnvironmentParameters.setObjectName(_fromUtf8("wpEnvironmentParameters"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.wpEnvironmentParameters)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widEnvironmentData = QtGui.QWidget(self.wpEnvironmentParameters)
        self.widEnvironmentData.setObjectName(_fromUtf8("widEnvironmentData"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widEnvironmentData)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lblTemperature = QtGui.QLabel(self.widEnvironmentData)
        self.lblTemperature.setObjectName(_fromUtf8("lblTemperature"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblTemperature)
        self.lblMoisture = QtGui.QLabel(self.widEnvironmentData)
        self.lblMoisture.setObjectName(_fromUtf8("lblMoisture"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblMoisture)
        self.lblPressure = QtGui.QLabel(self.widEnvironmentData)
        self.lblPressure.setObjectName(_fromUtf8("lblPressure"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblPressure)
        self.dsbTemperature = QtGui.QDoubleSpinBox(self.widEnvironmentData)
        self.dsbTemperature.setSingleStep(0.1)
        self.dsbTemperature.setProperty("value", 20.0)
        self.dsbTemperature.setObjectName(_fromUtf8("dsbTemperature"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.dsbTemperature)
        self.dsbMoisture = QtGui.QDoubleSpinBox(self.widEnvironmentData)
        self.dsbMoisture.setMaximum(100.0)
        self.dsbMoisture.setProperty("value", 30.0)
        self.dsbMoisture.setObjectName(_fromUtf8("dsbMoisture"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.dsbMoisture)
        self.dsbPressure = QtGui.QDoubleSpinBox(self.widEnvironmentData)
        self.dsbPressure.setDecimals(4)
        self.dsbPressure.setMaximum(200.0)
        self.dsbPressure.setSingleStep(0.1)
        self.dsbPressure.setProperty("value", 101.325)
        self.dsbPressure.setObjectName(_fromUtf8("dsbPressure"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.dsbPressure)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_5.addWidget(self.widEnvironmentData)
        newProjectWizard.addPage(self.wpEnvironmentParameters)
        self.wpSelectTube = QtGui.QWizardPage()
        self.wpSelectTube.setObjectName(_fromUtf8("wpSelectTube"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.wpSelectTube)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.wdSelectTube = QtGui.QWidget(self.wpSelectTube)
        self.wdSelectTube.setObjectName(_fromUtf8("wdSelectTube"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.wdSelectTube)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.rbCurrentTube = QtGui.QRadioButton(self.wdSelectTube)
        self.rbCurrentTube.setChecked(True)
        self.rbCurrentTube.setObjectName(_fromUtf8("rbCurrentTube"))
        self.verticalLayout_8.addWidget(self.rbCurrentTube)
        self.rbTubeFromFile = QtGui.QRadioButton(self.wdSelectTube)
        self.rbTubeFromFile.setObjectName(_fromUtf8("rbTubeFromFile"))
        self.verticalLayout_8.addWidget(self.rbTubeFromFile)
        self.rbNewTube = QtGui.QRadioButton(self.wdSelectTube)
        self.rbNewTube.setObjectName(_fromUtf8("rbNewTube"))
        self.verticalLayout_8.addWidget(self.rbNewTube)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addWidget(self.wdSelectTube)
        newProjectWizard.addPage(self.wpSelectTube)
        self.wpMeasurementParameters = QtGui.QWizardPage()
        self.wpMeasurementParameters.setObjectName(_fromUtf8("wpMeasurementParameters"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.wpMeasurementParameters)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.wdMeasurementParameters = QtGui.QWidget(self.wpMeasurementParameters)
        self.wdMeasurementParameters.setObjectName(_fromUtf8("wdMeasurementParameters"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.wdMeasurementParameters)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lblAmountMeans = QtGui.QLabel(self.wdMeasurementParameters)
        self.lblAmountMeans.setObjectName(_fromUtf8("lblAmountMeans"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblAmountMeans)
        self.sbMeanAmount = QtGui.QSpinBox(self.wdMeasurementParameters)
        self.sbMeanAmount.setMinimum(1)
        self.sbMeanAmount.setMaximum(10000)
        self.sbMeanAmount.setObjectName(_fromUtf8("sbMeanAmount"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.sbMeanAmount)
        self.lblFFTResolution = QtGui.QLabel(self.wdMeasurementParameters)
        self.lblFFTResolution.setObjectName(_fromUtf8("lblFFTResolution"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFFTResolution)
        self.dsbFFTResolution = QtGui.QDoubleSpinBox(self.wdMeasurementParameters)
        self.dsbFFTResolution.setMinimum(0.1)
        self.dsbFFTResolution.setMaximum(100.0)
        self.dsbFFTResolution.setSingleStep(0.1)
        self.dsbFFTResolution.setProperty("value", 1.0)
        self.dsbFFTResolution.setObjectName(_fromUtf8("dsbFFTResolution"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.dsbFFTResolution)
        self.lblFFTWindow = QtGui.QLabel(self.wdMeasurementParameters)
        self.lblFFTWindow.setObjectName(_fromUtf8("lblFFTWindow"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblFFTWindow)
        self.cbFFTWindow = QtGui.QComboBox(self.wdMeasurementParameters)
        self.cbFFTWindow.setObjectName(_fromUtf8("cbFFTWindow"))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.cbFFTWindow.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbFFTWindow)
        self.lblSignal = QtGui.QLabel(self.wdMeasurementParameters)
        self.lblSignal.setObjectName(_fromUtf8("lblSignal"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblSignal)
        self.cbSignalSelect = QtGui.QComboBox(self.wdMeasurementParameters)
        self.cbSignalSelect.setObjectName(_fromUtf8("cbSignalSelect"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbSignalSelect)
        self.lblMeasurementTime = QtGui.QLabel(self.wdMeasurementParameters)
        self.lblMeasurementTime.setObjectName(_fromUtf8("lblMeasurementTime"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblMeasurementTime)
        self.lblMeasurementTimeDisplay = QtGui.QLabel(self.wdMeasurementParameters)
        self.lblMeasurementTimeDisplay.setText(_fromUtf8(""))
        self.lblMeasurementTimeDisplay.setObjectName(_fromUtf8("lblMeasurementTimeDisplay"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.lblMeasurementTimeDisplay)
        self.lblOverlap = QtGui.QLabel(self.wdMeasurementParameters)
        self.lblOverlap.setObjectName(_fromUtf8("lblOverlap"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblOverlap)
        self.sbOverlap = QtGui.QSpinBox(self.wdMeasurementParameters)
        self.sbOverlap.setPrefix(_fromUtf8(""))
        self.sbOverlap.setProperty("value", 90)
        self.sbOverlap.setObjectName(_fromUtf8("sbOverlap"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.sbOverlap)
        self.verticalLayout_16.addLayout(self.formLayout_4)
        self.verticalLayout_6.addWidget(self.wdMeasurementParameters)
        newProjectWizard.addPage(self.wpMeasurementParameters)

        self.retranslateUi(newProjectWizard)
        QtCore.QMetaObject.connectSlotsByName(newProjectWizard)
        newProjectWizard.setTabOrder(self.editName, self.deDate)
        newProjectWizard.setTabOrder(self.deDate, self.teComment)
        newProjectWizard.setTabOrder(self.teComment, self.editMaterial)
        newProjectWizard.setTabOrder(self.editMaterial, self.dsbMaterialThickness)
        newProjectWizard.setTabOrder(self.dsbMaterialThickness, self.dsbDegreeOfCleaning)
        newProjectWizard.setTabOrder(self.dsbDegreeOfCleaning, self.dsbAmountOfScrub)
        newProjectWizard.setTabOrder(self.dsbAmountOfScrub, self.dsbThousandSeedWeight)
        newProjectWizard.setTabOrder(self.dsbThousandSeedWeight, self.dsbTemperature)
        newProjectWizard.setTabOrder(self.dsbTemperature, self.dsbMoisture)
        newProjectWizard.setTabOrder(self.dsbMoisture, self.dsbPressure)
        newProjectWizard.setTabOrder(self.dsbPressure, self.rbCurrentTube)
        newProjectWizard.setTabOrder(self.rbCurrentTube, self.rbTubeFromFile)
        newProjectWizard.setTabOrder(self.rbTubeFromFile, self.rbNewTube)
        newProjectWizard.setTabOrder(self.rbNewTube, self.sbMeanAmount)
        newProjectWizard.setTabOrder(self.sbMeanAmount, self.dsbFFTResolution)
        newProjectWizard.setTabOrder(self.dsbFFTResolution, self.sbOverlap)
        newProjectWizard.setTabOrder(self.sbOverlap, self.cbFFTWindow)
        newProjectWizard.setTabOrder(self.cbFFTWindow, self.cbSignalSelect)

    def retranslateUi(self, newProjectWizard):
        newProjectWizard.setWindowTitle(_translate("newProjectWizard", "Projektassistent", None))
        self.wpProjectData.setTitle(_translate("newProjectWizard", "Projektdaten", None))
        self.lblName.setText(_translate("newProjectWizard", "Name", None))
        self.lblDate.setText(_translate("newProjectWizard", "Datum", None))
        self.lblComment.setText(_translate("newProjectWizard", "Kommentar", None))
        self.wpMaterialParameters.setTitle(_translate("newProjectWizard", "Materialparameter", None))
        self.lblMaterial.setText(_translate("newProjectWizard", "Material", None))
        self.lblMaterialDepth.setText(_translate("newProjectWizard", "Materialstärke", None))
        self.lblDegreeOfCleaning.setText(_translate("newProjectWizard", "Reinigungsgrad", None))
        self.lblAmountOfScrub.setText(_translate("newProjectWizard", "Anteil Fraßmehl", None))
        self.lblTSeedWeight.setText(_translate("newProjectWizard", "TKG", None))
        self.dsbAmountOfScrub.setSuffix(_translate("newProjectWizard", " %", None))
        self.dsbDegreeOfCleaning.setSuffix(_translate("newProjectWizard", " %", None))
        self.dsbMaterialThickness.setSuffix(_translate("newProjectWizard", " mm", None))
        self.dsbThousandSeedWeight.setSuffix(_translate("newProjectWizard", " g", None))
        self.wpEnvironmentParameters.setTitle(_translate("newProjectWizard", "Umgebungsparamter", None))
        self.lblTemperature.setText(_translate("newProjectWizard", "Temperatur", None))
        self.lblMoisture.setText(_translate("newProjectWizard", "rel. Luftfeuchte", None))
        self.lblPressure.setText(_translate("newProjectWizard", "Luftdruck", None))
        self.dsbTemperature.setSuffix(_translate("newProjectWizard", " °C", None))
        self.dsbMoisture.setSuffix(_translate("newProjectWizard", " %", None))
        self.dsbPressure.setSuffix(_translate("newProjectWizard", " kPa", None))
        self.wpSelectTube.setTitle(_translate("newProjectWizard", "Messrohr Auswählen", None))
        self.rbCurrentTube.setText(_translate("newProjectWizard", "Aktuelles Rohr verwenden", None))
        self.rbTubeFromFile.setText(_translate("newProjectWizard", "Rohr aus Datei laden", None))
        self.rbNewTube.setText(_translate("newProjectWizard", "Neues Rohr erstellen", None))
        self.wpMeasurementParameters.setTitle(_translate("newProjectWizard", "Messungs-Parameter", None))
        self.lblAmountMeans.setText(_translate("newProjectWizard", "Anzahl Mittelungen", None))
        self.lblFFTResolution.setText(_translate("newProjectWizard", "FFT-Auflösung", None))
        self.dsbFFTResolution.setSuffix(_translate("newProjectWizard", " Hz", None))
        self.lblFFTWindow.setText(_translate("newProjectWizard", "FFT-Fenster", None))
        self.cbFFTWindow.setItemText(0, _translate("newProjectWizard", "Bartlett-Hann", None))
        self.cbFFTWindow.setItemText(1, _translate("newProjectWizard", "Bartlett", None))
        self.cbFFTWindow.setItemText(2, _translate("newProjectWizard", "Blackman", None))
        self.cbFFTWindow.setItemText(3, _translate("newProjectWizard", "Blackman-Harris", None))
        self.cbFFTWindow.setItemText(4, _translate("newProjectWizard", "Bohman", None))
        self.cbFFTWindow.setItemText(5, _translate("newProjectWizard", "Boxcar/Rechteck", None))
        self.cbFFTWindow.setItemText(6, _translate("newProjectWizard", "Dreieck", None))
        self.cbFFTWindow.setItemText(7, _translate("newProjectWizard", "Flat-Top", None))
        self.cbFFTWindow.setItemText(8, _translate("newProjectWizard", "Hamming", None))
        self.cbFFTWindow.setItemText(9, _translate("newProjectWizard", "Hann", None))
        self.cbFFTWindow.setItemText(10, _translate("newProjectWizard", "Parzen", None))
        self.lblSignal.setText(_translate("newProjectWizard", "Signal", None))
        self.lblMeasurementTime.setText(_translate("newProjectWizard", "Messdauer", None))
        self.lblOverlap.setText(_translate("newProjectWizard", "Überlappung", None))
        self.sbOverlap.setSuffix(_translate("newProjectWizard", " %", None))

